[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && chmod +x start.sh"

[deploy]
startCommand = "sh start.sh"
healthcheckPath = "/site"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[services.web]
port = "$PORT" 