[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && chmod +x start.sh"

[deploy]
startCommand = "sh start.sh"
healthcheckPath = "/"
healthcheckTimeout = 180
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[services.web]
port = "$PORT"
internal_port = 8080 