[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && chmod +x start.sh"

[deploy]
startCommand = "sh start.sh"
healthcheckPath = "/"
healthcheckTimeout = 180
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Web service configuration
[services.web]
port = "$PORT"
internal_port = 8080

# Telegram bot service configuration
[services.worker]
command = "python run_telegram_bot.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 